name: sporthub
description: "SportHub - Ứng dụng đặt sân thể thao và ghép kèo AI"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  google_generative_ai: ^0.4.6
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

