import '../../domain/entities/community_post.dart';
import '../../domain/entities/user_profile.dart';
import '../../domain/entities/venue.dart';
import '../../domain/entities/venue_addon.dart';

class SeedData {
  static const List<VenueAddonItem> sampleAddons = [
    // --- CẦU LÔNG (BADMINTON) ---
    VenueAddonItem(
      id: 'rent_badminton',
      name: 'Vợt Cầu Lông Yonex',
      description: 'Dòng Astrox 88D chuyên công căng sẵn 10.5kg',
      price: 30000,
      unit: 'cây',
      category: AddonCategory.rental,
      icon: '🏸',
      sportTypes: ['badminton'],
    ),
    VenueAddonItem(
      id: 'rent_machine',
      name: 'Máy Bắn Cầu Tự Động',
      description: 'Luyện tập phản xạ và kỹ thuật đa hướng',
      price: 80000,
      unit: 'giờ',
      category: AddonCategory.rental,
      icon: '🤖',
      sportTypes: ['badminton'],
    ),
    VenueAddonItem(
      id: 'gear_shuttle_tube',
      name: 'Ống Cầu Lông Hải Yến (12 quả)',
      description: 'Ống 12 quả bền đẹp chuẩn thi đấu',
      price: 240000,
      unit: 'ống',
      category: AddonCategory.gear,
      icon: '🏸',
      sportTypes: ['badminton'],
    ),
    VenueAddonItem(
      id: 'gear_shuttle_single',
      name: 'Quả Cầu Lông Lẻ Hải Yến',
      description: 'Cầu lông thi đấu cánh thẳng đầm tay',
      price: 22000,
      unit: 'quả',
      category: AddonCategory.gear,
      icon: '🏸',
      sportTypes: ['badminton'],
    ),

    // --- PICKLEBALL ---
    VenueAddonItem(
      id: 'rent_pickleball',
      name: 'Vợt Pickleball Carbon Joola',
      description: 'Mặt nhám carbon chuẩn thi đấu USAPA',
      price: 40000,
      unit: 'cây',
      category: AddonCategory.rental,
      icon: '🏓',
      sportTypes: ['pickleball'],
    ),
    VenueAddonItem(
      id: 'gear_pickle_ball',
      name: 'Bóng Pickleball Franklin X-40',
      description: 'Bóng ngoài trời 40 lỗ độ nảy chuẩn',
      price: 45000,
      unit: 'quả',
      category: AddonCategory.gear,
      icon: '🟡',
      sportTypes: ['pickleball'],
    ),

    // --- BÓNG ĐÁ (FOOTBALL) ---
    VenueAddonItem(
      id: 'rent_football_ball',
      name: 'Bóng Đá Thi Đấu Động Lực',
      description: 'Bóng số 5 da PU tiêu chuẩn thi đấu sân 5-7',
      price: 30000,
      unit: 'trận',
      category: AddonCategory.rental,
      icon: '⚽',
      sportTypes: ['football'],
    ),
    VenueAddonItem(
      id: 'rent_football_bibs',
      name: 'Bộ Áo Bib Phân Đội (10 áo)',
      description: 'Áo lưới thoáng khí chia 2 đội bóng màu dạ quang',
      price: 20000,
      unit: 'bộ',
      category: AddonCategory.rental,
      icon: '🎽',
      sportTypes: ['football'],
    ),
    VenueAddonItem(
      id: 'rent_football_gloves',
      name: 'Găng Tay Thủ Môn Có Xương',
      description: 'Găng trợ lực chống trật khớp ngón tay và dính bóng',
      price: 25000,
      unit: 'đôi',
      category: AddonCategory.rental,
      icon: '🧤',
      sportTypes: ['football'],
    ),
    VenueAddonItem(
      id: 'rent_football_shoes',
      name: 'Giày Đá Bóng Sân Cỏ TF (Size 39-44)',
      description: 'Đế đinh dăm cao su bám sân cỏ nhân tạo chống trượt',
      price: 30000,
      unit: 'đôi',
      category: AddonCategory.rental,
      icon: '👟',
      sportTypes: ['football'],
    ),
    VenueAddonItem(
      id: 'drink_ice_bucket',
      name: 'Thùng Đá Ướp Lạnh + Ca Nước',
      description: 'Thùng đá giữ nhiệt lớn phục vụ giải khát cả trận',
      price: 20000,
      unit: 'thùng',
      category: AddonCategory.beverage,
      icon: '🧊',
      sportTypes: ['football'],
    ),
    VenueAddonItem(
      id: 'gear_football_tape',
      name: 'Băng Keo Thể Thao Quấn Cổ Chân',
      description: 'Chống lật sơ mi và cố định cổ chân khi đá',
      price: 15000,
      unit: 'cuộn',
      category: AddonCategory.gear,
      icon: '🩹',
      sportTypes: ['football'],
    ),
    VenueAddonItem(
      id: 'gear_cold_spray',
      name: 'Bình Xịt Lạnh Giảm Đau Tức Thì',
      description: 'Xịt lạnh cấp tốc giảm sưng đau va chạm thể thao',
      price: 60000,
      unit: 'chai',
      category: AddonCategory.gear,
      icon: '❄️',
      sportTypes: ['football', 'badminton', 'pickleball'],
    ),

    // --- PHỤ KIỆN VỢT DÙNG CHUNG (CẦU LÔNG & PICKLEBALL) ---
    VenueAddonItem(
      id: 'gear_grip',
      name: 'Quấn Cán Vợt Thấm Mồ Hôi',
      description: 'Chống trơn trượt êm tay thấm hút tốt',
      price: 25000,
      unit: 'cái',
      category: AddonCategory.gear,
      icon: '🎾',
      sportTypes: ['badminton', 'pickleball'],
    ),

    // --- NƯỚC UỐNG DÙNG CHUNG CHO TẤT CẢ MÔN ---
    VenueAddonItem(
      id: 'drink_pocari',
      name: 'Pocari Sweat Bù Khoáng',
      description: 'Chai 500ml ướp lạnh bổ sung điện giải',
      price: 15000,
      unit: 'chai',
      category: AddonCategory.beverage,
      icon: '🥤',
      sportTypes: ['all'],
    ),
    VenueAddonItem(
      id: 'drink_aquafina',
      name: 'Nước Khoáng Aquafina',
      description: 'Chai 500ml tinh khiết mát lạnh',
      price: 10000,
      unit: 'chai',
      category: AddonCategory.beverage,
      icon: '💧',
      sportTypes: ['all'],
    ),
    VenueAddonItem(
      id: 'drink_redbull',
      name: 'Nước Tăng Lực Redbull',
      description: 'Lon 250ml nạp năng lượng nhanh',
      price: 20000,
      unit: 'lon',
      category: AddonCategory.beverage,
      icon: '⚡',
      sportTypes: ['all'],
    ),
  ];

  static const List<Venue> sampleVenues = [
    Venue(
      id: 'venue_bt_01',
      name: 'CLB Cầu Lông & Pickleball Bình Thạnh Sport',
      sportTypes: ['badminton', 'pickleball'],
      address: '123 Chu Văn An, Phường 12',
      district: 'Bình Thạnh',
      courtCount: 6,
      hourlyRate: 150000.0,
      rating: 4.8,
      reviewCount: 142,
      imageUrls: [
        'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
      ],
      amenities: ['Bãi đỗ ô tô', 'Máy lạnh', 'Căn tin', 'WiFi'],
    ),
    Venue(
      id: 'venue_td_02',
      name: 'Thảo Điền Pickleball Hub',
      sportTypes: ['pickleball'],
      address: '45 Quốc Hương, Thảo Điền',
      district: 'Thủ Đức',
      courtCount: 8,
      hourlyRate: 200000.0,
      rating: 4.9,
      reviewCount: 98,
      imageUrls: [
        'https://images.unsplash.com/photo-1599474924187-334a4ae5bd3c?w=800',
      ],
      amenities: ['Tủ locker', 'Phòng tắm nóng lạnh', 'Cho thuê vợt', 'Huấn luyện viên'],
    ),
    Venue(
      id: 'venue_q7_03',
      name: 'Sân Bóng Đá Mini Nam Sài Gòn',
      sportTypes: ['football'],
      address: '78 Nguyễn Hữu Thọ, Tân Hưng',
      district: 'Quận 7',
      courtCount: 4,
      hourlyRate: 280000.0,
      rating: 4.7,
      reviewCount: 215,
      imageUrls: [
        'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800',
      ],
      amenities: ['Đèn chiếu sáng tiêu chuẩn', 'Trọng tài', 'Bãi giữ xe rộng'],
    ),
    Venue(
      id: 'venue_q1_04',
      name: 'CLB Cầu Lông Tao Đàn - Quận 1',
      sportTypes: ['badminton'],
      address: '1 Huyền Trân Công Chúa, Phường Bến Thành',
      district: 'Quận 1',
      courtCount: 5,
      hourlyRate: 160000.0,
      rating: 4.9,
      reviewCount: 180,
      imageUrls: [
        'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
      ],
      amenities: ['Trung tâm Q1', 'Máy lạnh', 'Căn tin', 'Chỗ đậu xe máy'],
    ),
    Venue(
      id: 'venue_tb_05',
      name: 'Khu Liên Hợp Thể Thao Tân Bình Arena',
      sportTypes: ['badminton', 'football', 'pickleball'],
      address: '448 Hoàng Văn Thụ, Phường 4',
      district: 'Tân Bình',
      courtCount: 10,
      hourlyRate: 180000.0,
      rating: 4.8,
      reviewCount: 156,
      imageUrls: [
        'https://images.unsplash.com/photo-1599474924187-334a4ae5bd3c?w=800',
      ],
      amenities: ['Cụm 10 sân', 'Bãi đỗ ô tô', 'Căng tin thể thao', 'Tắm nóng lạnh'],
    ),
  ];

  static const List<UserProfile> demoUsers = [
    UserProfile(
      userId: 'user_demo_01',
      fullName: 'Nguyễn Văn An',
      phone: '0909 123 456',
      preferredSport: 'pickleball',
      skillLevel: 'Intermediate',
      district: 'Bình Thạnh',
      playTimePreference: 'Buổi tối (18:00 - 21:00)',
      matchesPlayed: 18,
      reputationRating: 4.9,
      onTimeRate: 98,
    ),
    UserProfile(
      userId: 'user_demo_02',
      fullName: 'Lê Minh',
      phone: '0918 888 999',
      preferredSport: 'pickleball',
      skillLevel: 'Advanced',
      district: 'Thủ Đức',
      playTimePreference: 'Tối Thứ Bảy (19:00 - 21:00)',
      matchesPlayed: 32,
      reputationRating: 5.0,
      onTimeRate: 100,
    ),
    UserProfile(
      userId: 'user_demo_03',
      fullName: 'Trần Thuỳ Linh',
      phone: '0977 666 555',
      preferredSport: 'badminton',
      skillLevel: 'Beginner',
      district: 'Quận 1',
      playTimePreference: 'Sáng Chủ Nhật (06:30 - 08:30)',
      matchesPlayed: 5,
      reputationRating: 4.8,
      onTimeRate: 95,
    ),
    UserProfile(
      userId: 'user_owner_01',
      fullName: 'Trần Văn Chủ Sân',
      phone: '0988 888 777',
      preferredSport: 'badminton',
      skillLevel: 'Advanced',
      district: 'Quận 1',
      playTimePreference: 'Cả ngày (06:00 - 22:00)',
      matchesPlayed: 120,
      reputationRating: 5.0,
      onTimeRate: 100,
    ),
  ];

  static const Map<String, dynamic> sampleUserProfile = {
    'userId': 'user_demo_01',
    'fullName': 'Nguyễn Văn An',
    'phone': '0909 123 456',
    'preferredSport': 'pickleball',
    'district': 'Bình Thạnh',
    'skillLevel': 'Intermediate',
    'playTimePreference': 'Buổi tối (18:00 - 21:00)',
    'matchesPlayed': 18,
    'reputationRating': 4.9,
    'onTimeRate': 98,
  };

  static const List<Map<String, dynamic>> sampleMatchmakingPosts = [
    {
      'id': 'post_match_01',
      'title': 'Tìm bạn đánh đôi Pickleball giao lưu vui vẻ',
      'authorName': 'Trần Hoàng',
      'sportType': 'pickleball',
      'district': 'Bình Thạnh',
      'skillLevel': 'Intermediate',
      'venueName': 'CLB Bình Thạnh Sport',
      'scheduledTime': '18:30 - 20:30 Thứ Sáu',
      'requiredPlayers': 2,
      'currentPlayers': 2,
      'note': 'Tìm cặp đánh đôi cọ xát kinh nghiệm, giao lưu vui vẻ là chính.',
    },
    {
      'id': 'post_match_02',
      'title': 'Tuyển 1 slot đánh Pickleball buổi tối Thảo Điền',
      'authorName': 'Lê Minh',
      'sportType': 'pickleball',
      'district': 'Thủ Đức',
      'skillLevel': 'Advanced',
      'venueName': 'Thảo Điền Pickleball Hub',
      'scheduledTime': '19:00 - 21:00 Thứ Bảy',
      'requiredPlayers': 1,
      'currentPlayers': 3,
      'note': 'Kèo trình độ DUPR 3.5+ đánh đôi tốc độ cao.',
    },
    {
      'id': 'post_match_03',
      'title': 'Giao lưu Cầu lông phong trào cuối tuần',
      'authorName': 'Phạm Đức',
      'sportType': 'badminton',
      'district': 'Bình Thạnh',
      'skillLevel': 'Beginner',
      'venueName': 'Sân Chu Văn An',
      'scheduledTime': '08:00 - 10:00 Chủ Nhật',
      'requiredPlayers': 3,
      'currentPlayers': 1,
      'note': 'Chào đón người mới bắt đầu, rèn luyện sức khỏe cuối tuần.',
    },
    {
      'id': 'post_match_04',
      'title': 'Tìm đội đá bóng mini 5 người sân Nam Sài Gòn',
      'authorName': 'Võ Quốc',
      'sportType': 'football',
      'district': 'Quận 7',
      'skillLevel': 'Intermediate',
      'venueName': 'Sân Bóng Đá Mini Nam Sài Gòn',
      'scheduledTime': '19:30 - 21:00 Thứ Tư',
      'requiredPlayers': 5,
      'currentPlayers': 5,
      'note': 'Tìm đội bạn thi đấu sân cỏ nhân tạo giao lưu fair-play.',
    },
    {
      'id': 'post_match_05',
      'title': 'Kèo Pickleball dưỡng sinh sáng Chủ Nhật',
      'authorName': 'Đặng Ngọc',
      'sportType': 'pickleball',
      'district': 'Quận 1',
      'skillLevel': 'Beginner',
      'venueName': 'Sân Hoa Lư',
      'scheduledTime': '06:30 - 08:30 Chủ Nhật',
      'requiredPlayers': 2,
      'currentPlayers': 2,
      'note': 'Vận động buổi sáng thư giãn, không đặt nặng thành tích.',
    },
  ];

  static const List<CommunityPost> sampleCommunityPosts = [
    CommunityPost(
      id: 'post_01',
      title: 'Tuyển 2 bạn đánh cầu lông tối nay',
      authorId: 'user_host_01',
      authorName: 'Quốc Anh',
      authorAvatar: 'QA',
      sportType: 'badminton',
      district: 'Bình Thạnh',
      skillLevel: 'Trung bình',
      venueName: 'CLB Cầu Lông Bình Thạnh Sport',
      scheduledTime: '19:00 - 21:00 Hôm nay',
      requiredPlayers: 4,
      currentPlayers: 2,
      shareFee: 40000,
      note: 'Giao lưu vui vẻ, thiếu 2 chân đánh đôi sân thảm tiêu chuẩn.',
      imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
      likesCount: 12,
      isLiked: false,
      isJoined: false,
      requiresApproval: false,
    ),
    CommunityPost(
      id: 'post_02',
      title: 'Tuyển 1 slot đánh Pickleball buổi tối Thảo Điền',
      authorId: 'user_host_02',
      authorName: 'Lê Minh',
      authorAvatar: 'LM',
      sportType: 'pickleball',
      district: 'Thủ Đức',
      skillLevel: 'Nâng cao',
      venueName: 'Thảo Điền Pickleball Hub',
      scheduledTime: '19:00 - 21:00 Thứ Bảy',
      requiredPlayers: 4,
      currentPlayers: 3,
      shareFee: 60000,
      note: 'Kèo trình độ DUPR 3.5+ đánh đôi tốc độ cao.',
      imageUrl: 'https://images.unsplash.com/photo-1599474924187-334a4ae5bd3c?w=800',
      likesCount: 8,
      isLiked: false,
      isJoined: false,
    ),
    CommunityPost(
      id: 'post_03',
      title: 'Tìm 3 bạn đá bóng mini 5 người sân Nam Sài Gòn',
      authorId: 'user_host_03',
      authorName: 'Võ Quốc',
      authorAvatar: 'VQ',
      sportType: 'football',
      district: 'Quận 7',
      skillLevel: 'Trung bình',
      venueName: 'Sân Bóng Đá Mini Nam Sài Gòn',
      scheduledTime: '19:30 - 21:00 Thứ Tư',
      requiredPlayers: 10,
      currentPlayers: 7,
      shareFee: 50000,
      note: 'Đội thiếu người đá sân cỏ nhân tạo, giao lưu fair-play có áo bib và nước mát.',
      imageUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800',
      likesCount: 24,
      isLiked: true,
      isJoined: false,
      requiresApproval: false,
    ),
    CommunityPost(
      id: 'post_04',
      title: 'Kèo Pickleball dưỡng sinh sáng Chủ Nhật',
      authorId: 'user_host_04',
      authorName: 'Đặng Ngọc',
      authorAvatar: 'DN',
      sportType: 'pickleball',
      district: 'Quận 1',
      skillLevel: 'Cơ bản',
      venueName: 'CLB Cầu Lông & Pickleball Tao Đàn',
      scheduledTime: '06:30 - 08:30 Chủ Nhật',
      requiredPlayers: 4,
      currentPlayers: 2,
      shareFee: 45000,
      note: 'Vận động buổi sáng thư giãn, chào đón người mới tập chơi.',
      imageUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800',
      likesCount: 5,
      isLiked: false,
      isJoined: false,
    ),
    CommunityPost(
      id: 'post_05',
      title: 'Giao lưu Cầu lông phong trào cuối tuần',
      authorId: 'user_host_05',
      authorName: 'Phạm Đức',
      authorAvatar: 'PĐ',
      sportType: 'badminton',
      district: 'Tân Bình',
      skillLevel: 'Cơ bản',
      venueName: 'Khu Liên Hợp Thể Thao Tân Bình Arena',
      scheduledTime: '08:00 - 10:00 Chủ Nhật',
      requiredPlayers: 4,
      currentPlayers: 1,
      shareFee: 35000,
      note: 'Rèn luyện sức khỏe cuối tuần, không áp lực điểm số.',
      imageUrl: 'https://images.unsplash.com/photo-1521537634581-0dced2fed2a8?w=800',
      likesCount: 15,
      isLiked: false,
      isJoined: false,
    ),
  ];
}
